# Recipe needed to limit python versions.

package:
  name: iminuit
  version: "{{version}}"

source:
  fn: iminuit-{{version}}.tar.gz
  url: https://pypi.python.org/packages/source/i/iminuit/iminuit-{{version}}.tar.gz
  md5: {{md5}}
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - iminuit = iminuit:main
    #
    # Would create an entry point called iminuit that calls iminuit.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - python <3

  run:
    - python
    - python <3

test:
  # Python imports
  imports:
    - iminuit

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://iminuit.github.io/iminuit/
  license: GNU General Public License (GPL) or MIT License
  summary: 'Interactive Minimization Tools based on MINUIT'

extra:
    # List of platforms on which build of this package is expected to succeed.
    # Allowed options are those in binstar subdir:
    #       osx-64, linux-32, linux-64, win-32, win-64
    # platforms:
    #     - osx-64
    #     - linux-64
    # List of python versions (in CONDA_PY format) for which this package
    # should be built.
    # pythons:
    #     - 27
# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
