# Recipe template needed to skip the pca_gal script, which fails on Windows.
package:
  name: pydl
  version: "{{version}}"

source:
  fn: pydl-{{version}}.tar.gz
  url: https://pypi.python.org/packages/source/p/pydl/pydl-{{version}}.tar.gz
  md5: {{md5}}
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pydl = pydl:main
    #
    # Would create an entry point called pydl that calls pydl.main()

    - get_juldate = pydl.goddard.astro.get_juldate:get_juldate_main
    - hogg_iau_name = pydl.pydlutils.misc.hogg_iau_name:hogg_iau_name_main
    - pca_gal = pydl.pydlspec2d.spec1d.pca_gal:pca_gal_main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - astropy

  run:
    - python
    - astropy

test:
  # Python imports
  imports:
    - pydl
    - pydl.goddard
    - pydl.goddard.astro
    - pydl.goddard.astro.tests
    - pydl.goddard.math
    - pydl.goddard.math.tests
    - pydl.goddard.misc
    - pydl.goddard.misc.tests
    - pydl.photoop
    - pydl.photoop.photoobj
    - pydl.photoop.photoobj.tests
    - pydl.photoop.sdssio
    - pydl.photoop.sdssio.tests
    - pydl.photoop.window
    - pydl.pydlspec2d
    - pydl.pydlspec2d.spec1d
    - pydl.pydlspec2d.spec1d.tests
    - pydl.pydlspec2d.spec2d
    - pydl.pydlspec2d.spec2d.tests
    - pydl.pydlutils
    - pydl.pydlutils.bspline
    - pydl.pydlutils.bspline.tests
    - pydl.pydlutils.cooling
    - pydl.pydlutils.coord
    - pydl.pydlutils.coord.tests
    - pydl.pydlutils.image
    - pydl.pydlutils.mangle
    - pydl.pydlutils.mangle.tests
    - pydl.pydlutils.math
    - pydl.pydlutils.math.tests
    - pydl.pydlutils.misc
    - pydl.pydlutils.misc.tests
    - pydl.pydlutils.sdss
    - pydl.pydlutils.sdss.tests
    - pydl.pydlutils.spheregroup
    - pydl.pydlutils.spheregroup.tests
    - pydl.pydlutils.trace
    - pydl.pydlutils.trace.tests
    - pydl.pydlutils.yanny
    - pydl.pydlutils.yanny.tests
    - pydl.tests

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - get_juldate --help
    - hogg_iau_name --help
    # - pca_gal --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/weaverba137/pydl
  license: BSD License
  summary: 'Astropy affiliated package'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
