# Need recipe to patch on Windows + python 3

package:
  name: ginga
  version: "{{version}}"

source:
  fn: ginga-{{version}}.tar.gz
  url: https://pypi.python.org/packages/source/g/ginga/ginga-{{version}}.tar.gz
  md5: {{md5}}
  patches:
   # List any patch files here
    - setup.diff # [win and py3k]

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - ginga = ginga:main
    #
    # Would create an entry point called ginga that calls ginga.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - python >2.6
    - setuptools
    - numpy >=1.7

  run:
    - python
    - python >2.6
    - numpy >=1.7

test:
  # Python imports
  imports:
    - ginga
    - ginga.aggw
    - ginga.base
    - ginga.cairow
    - ginga.canvas
    - ginga.cvw
    - ginga.doc
    - ginga.gtkw
    - ginga.gtkw.plugins
    - ginga.gtkw.tests
    - ginga.icons
    - ginga.misc
    - ginga.misc.plugins
    - ginga.mockw
    - ginga.mplw
    - ginga.qtw
    - ginga.qtw.plugins
    - ginga.qtw.tests
    - ginga.tests
    - ginga.tkw
    - ginga.util
    - ginga.web
    - ginga.web.pgw
    - ginga.web.pgw.js
    - ginga.web.pgw.templates

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://ejeschke.github.com/ginga
  license: BSD License
  summary: 'An astronomical image viewer and toolkit.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
