# Need recipe because import tests must be skipped...they fail unless montage
# is installed.
#
# Also, astropy is a build requirement but is not listed as such.

package:
  name: montage-wrapper
  version: "{{version}}"

source:
  fn: montage-wrapper-{{version}}.tar.gz
  url: https://pypi.python.org/packages/source/m/montage-wrapper/montage-wrapper-{{version}}.tar.gz
  md5: {{md5}}
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - astroml = astroml:main
    #
    # Would create an entry point called astroml that calls astroml.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - astropy  # TODO Can be removed in next version of montage-wrapper

  run:
    - python
    - astropy

## SKIP TESTS BECAUSE the only import, of montage-wrapper, will fail if
## montage is not installed.

# test:
#   # Python imports
#   imports:
#     - montage_wrapper

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://astropy.org/montage-wrapper/
  license: BSD License
  summary: 'Python wrapper for the Montage mosaicking toolkit'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
