# Recipe needed to:
#
# + Include numpy as a dependency
# + Skip a couple of the import tests
package:
  name: asdf
  version: "{{version}}"

source:
  fn: asdf-{{version}}.tar.gz
  url: https://pypi.python.org/packages/source/a/asdf/asdf-{{version}}.tar.gz
  md5: {{md5}}
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - asdf = asdf:main
    #
    # Would create an entry point called asdf that calls asdf.main()

    - asdftool = pyasdf.commands.main:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pyyaml >=3.10
    - jsonschema >=2.3.0
    - six >=1.9.0
    - pytest >=2.7.2

  run:
    - python
    - pyyaml >=3.10
    - jsonschema >=2.3.0
    - six >=1.9.0
    - pytest >=2.7.2
    - numpy

test:
  # Python imports
  imports:
    - pyasdf
    - pyasdf.commands
    - pyasdf.commands.tests
    - pyasdf.compat
    # - pyasdf.compat._odict_py2
    - pyasdf.extern
    # - pyasdf.reference_files
    # - pyasdf.schemas
    - pyasdf.tags
    - pyasdf.tags.core
    - pyasdf.tags.core.tests
    - pyasdf.tags.fits
    - pyasdf.tags.fits.tests
    - pyasdf.tags.time
    - pyasdf.tags.time.tests
    - pyasdf.tags.transform
    - pyasdf.tags.transform.tests
    - pyasdf.tags.unit
    - pyasdf.tags.unit.tests
    - pyasdf.tags.wcs
    - pyasdf.tags.wcs.tests
    - pyasdf.tests

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - asdftool --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/spacetelescope/pyasdf
  license: BSD
  summary: 'Python tools to handle ASDF files'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
