{% set data = load_setup_py_data() %}

package:
    name: extruder
    version: {{data.get('version')}}

source:
    path: ../

build:
    script: python setup.py install  --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
        - setuptools
        - astropy-helpers
        - astropy

    run:
        - python
        - setuptools
        - conda
        - conda-build >=2.1
        - anaconda-client
        - six
        - ruamel.yaml
        - github3.py
        - gitpython

test:
  imports:
    - extruder
  commands:
    - extrude_template --help
    - extrude_recipes --help
    - copy_packages --help
    - conda_forge_feedstock_cloner --help

about:
  license: BSD-3
  home: https://github.com/astropy/conda-build-tools
