# astroml has no dependencies listed in setup.py, so need recipe.

package:
  name: astroml
  version: "{{version}}"

source:
  fn: astroML-{{version}}.tar.gz
  url: https://pypi.python.org/packages/source/a/astroML/astroML-{{version}}.tar.gz
  md5: {{md5}}
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - astroml = astroml:main
    #
    # Would create an entry point called astroml that calls astroml.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - python >=2.6|>=3.3

  run:
    - python
    - python >=2.6|>=3.3
    - numpy >=1.4
    - scipy >=0.7
    - matplotlib >=0.99
    - scikit-learn >=0.10
    - astropy >=0.2.5

test:
  # Python imports
  imports:
    - astroML
    - astroML.classification
    - astroML.clustering
    - astroML.clustering.tests
    - astroML.datasets
    - astroML.datasets.tools
    - astroML.density_estimation
    - astroML.density_estimation.tests
    - astroML.dimensionality
    - astroML.dimensionality.tests
    - astroML.linear_model
    - astroML.plotting
    - astroML.plotting.tests
    - astroML.stats
    - astroML.stats.tests
    - astroML.tests
    - astroML.time_series
    - astroML.time_series.tests
    - astroML

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://astroML.github.com
  license: BSD License
  summary: 'tools for machine learning and data mining in Astronomy'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
