# Recipe template is needed to add asdf to runtime requirements.
package:
  name: gwcs
  version: "{{version}}"

source:
  fn: gwcs-{{version}}.tar.gz
  url: https://pypi.python.org/packages/source/g/gwcs/gwcs-{{version}}.tar.gz
  md5: {{md5}}
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - gwcs = gwcs:main
    #
    # Would create an entry point called gwcs that calls gwcs.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - astropy

  run:
    - python
    - astropy
    - asdf

test:
  # Python imports
  imports:
    - gwcs
    - gwcs.tags
    - gwcs.tags.tests
    - gwcs.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://gwcs.readthedocs.org/en/latest/
  license: BSD
  summary: 'Generalized World Coordinate System'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
